### PR TITLE
Document examples

### PR DESCRIPTION
**Pull request by sotojuan**
Probably a better place to put this and better way to write it, but figured I'd start!

### CODE REVIEW

**Comment by mxstbr** [comment]
Lets move it below the `Plugins` section, since that's really the most important one, but other than that this is A+!

**Comment by sotojuan** [comment]
Done!

**Comment by nikgraf** [comment]
thx @sotojuan 🙌

**Comment by mxstbr** [comment]
Awesome @sotojuan!

**Pull request merged**
