### PR TITLE
Novascreen windows support

### PR DESCRIPTION
**Pull request by nikgraf**

### CODE REVIEW

**Comment by novascreen** [comment]
@nikgraf when can i expect a new version being published that includes this?

**Comment by mxstbr** [comment]
Let's publish one asap!  Sorry for the delay!

**Comment by novascreen** [comment]
@mxstbr ping

**Comment by ingro** [comment]
Sorry to write here but any ETA on this? Would love to try this!

**Comment by mxstbr** [comment]
Totally fell off my grid, absolutely my bad. @nikgraf have time to prepare a release?

**Comment by nikgraf** [comment]
@mxstbr yep, this evening (I believe so)

**Comment by mhauken** [comment]
Hi, @nikgraf and @mxstbr! Thanks for a great week in Las Palmas!
How is the possibility of publishing this pull-request asap?
Would love to test it out in a project I'm working on where Windows-support is a deal-breaker.

**Pull request merged**
