### PR TITLE
Initial commit. Merge propTypeData with custom meta data.

### PR DESCRIPTION
**Pull request by busypeoples**

### CODE REVIEW

**Comment by nikgraf** [comment]
nice, will take a look a bit later today! thx @busypeoples

**Comment by mxstbr** [comment]
This is a great start!

IMO making this a shared util with unit tests would be necessary to land it. I reckon there's tons of edge cases that need to be taken care which we can't accurately asses are taken care of just from looking at it. Would you mind doing that?

**Comment by busypeoples** [comment]
This should give you a high level idea of what's going on. Maybe @steos could optimize the enum and shape generation with a randomizer?

**Comment by nikgraf** [comment]
@busypeoples I'm thinking about preventing people to pick nested structures like objects & arrays in the interface. It introduces so much complexity. Defining it in your code as Flow or PropTypes should be ok.

Changing an avatarUrl prop to avatar was the use-case why we need this in the first place and this is already covered …

What do you think?

**Comment by busypeoples** [comment]
@nikgraf preventing nested structures makes sense.

**Comment by nikgraf** [comment]
I cherry picked one change, but left out the other stuff.

**Pull request closed without merging**
