### PR TITLE
Added modal confirmation on variation delete

### PR DESCRIPTION
**Pull request by nkalichynskyi**

### CODE REVIEW

**Comment by mxstbr** [comment]
Awesome thanks!

**Comment by nikgraf** [comment]
@mxstbr I reviewed it locally, works great!

thx @nkalichynskyi - well done 👏 up for more? 😃

**Comment by nkalichynskyi** [comment]
@nikgraf of course, it's interesting project to work on :smile:

**Comment by nikgraf** [comment]
@nkalichynskyi this might be a good next one: https://github.com/carteb/carte-blanche/issues/273

but feel free to pick whatever you like 👍 
We also can pair program sometime next week and & introduce your to some of the more complex parts parts of the tool

**Comment by nkalichynskyi** [comment]
@nikgraf sounds great, I'm still on my way home from ReactEurope, so I'll take some new issues as soon as I'll get home and we can do some pair program after that.

**Pull request merged**
