### PR TITLE
Fix example

### PR DESCRIPTION
**Pull request by fredjens**
Removed autoprefixer so it is possible to run example. Webpack 2 no longer allows custom properties in configuration.

### CODE REVIEW

**Comment by nikgraf** [comment]
@fredjens sorry have been busy with work more than I expected lately. The CI still fails with: `Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.`

**Comment by nikgraf** [comment]
Happy to merged it once the CI works fine

**Comment by fredjens** [comment]
This problem is actually in the React plugin and not the example, but it's the same problem, so it make sense to fix it here too.

**Comment by nikgraf** [comment]
thx @fredjens, now you need a release from us, right?

**Comment by fredjens** [comment]
Cool! I actually think there's a few more things that needs to be fixed... But if you release a minor in the meantime, it's cool :)

**Pull request merged**
