### PR TITLE
Saving notification

### PR DESCRIPTION
**Pull request by lithin**
Addresses #305 

Saving label appears on the "Edit variation" form whenever user starts typing and disappears when everything is saved.

### CODE REVIEW

**Comment by nikgraf** [comment]
Nice! 👏 
@lithin can you fix this one linting error and move the styles to css modules?

```
/home/travis/build/carteb/carte-blanche/plugins/react/frontend/components/common/SavingLabel/index.js
  10:27  error  Unexpected block statement surrounding arrow body  arrow-body-style
```

**Comment by mxstbr** [comment]
Awesomeeee

**Comment by lithin** [comment]
It's hopefully okay now :) I got confused by the RandomButton styles...

**Comment by mxstbr** [comment]
Awesome thanks!

**Pull request merged**
